baseurl                  = "https://miraisahara.com"
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Mirai Sahara"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "ms.ico"
    homepage             = "Home"                           # What to call the home page link, link will not be rendered if empty
    footerText           = "Made with Hugo"

# Metadata for Open Graph and Twitter
    description          = "Mirai."               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Mirai"
    # rss                = ""

[[params.mainMenu]]
    link = "/about"
    text = "About Me"

[[params.mainMenu]]
    link = "/done"
    text = "Things I've Done"

[[params.mainMenu]]
    link = "/like"
    text = "Things I Like"

[imaging]
    quality = 75
